import { Destination, SpecialOffer, Testimonial } from '@/types';

export const popularDestinations: Destination[] = [
  {
    id: 1,
    name: 'Santorini, Greece',
    location: 'Greece',
    description: 'Experience the stunning white-washed buildings and breathtaking sunsets over the Aegean Sea.',
    image: 'https://images.pexels.com/photos/1010657/pexels-photo-1010657.jpeg',
    price: 1299,
    featured: true,
  },
  {
    id: 2,
    name: 'Bali, Indonesia',
    location: 'Indonesia',
    description: 'Discover the perfect blend of beautiful beaches, lush rice terraces, and spiritual temples.',
    image: 'https://images.pexels.com/photos/3225531/pexels-photo-3225531.jpeg',
    price: 999,
    featured: false,
  },
  {
    id: 3,
    name: 'Kyoto, Japan',
    location: 'Japan',
    description: 'Immerse yourself in traditional Japanese culture with ancient temples and beautiful gardens.',
    image: 'https://images.pexels.com/photos/5759992/pexels-photo-5759992.jpeg',
    price: 1499,
    featured: true,
  },
  {
    id: 4,
    name: 'Machu Picchu, Peru',
    location: 'Peru',
    description: 'Explore the ancient Incan citadel set high in the Andes Mountains, a UNESCO World Heritage site.',
    image: 'https://images.pexels.com/photos/2929906/pexels-photo-2929906.jpeg',
    price: 1799,
    featured: false,
  },
  {
    id: 5,
    name: 'Amalfi Coast, Italy',
    location: 'Italy',
    description: 'Enjoy the stunning coastline, charming villages, and delicious Italian cuisine.',
    image: 'https://images.pexels.com/photos/4428285/pexels-photo-4428285.jpeg',
    price: 1399,
    featured: true,
  },
  {
    id: 6,
    name: 'Marrakech, Morocco',
    location: 'Morocco',
    description: 'Get lost in the vibrant markets, admire the stunning architecture, and experience Moroccan hospitality.',
    image: 'https://images.pexels.com/photos/4151484/pexels-photo-4151484.jpeg',
    price: 899,
    featured: false,
  },
];

export const specialOffers: SpecialOffer[] = [
  {
    id: 1,
    title: 'Romantic Santorini Getaway',
    description: '7 days exploring the beautiful Greek island with luxury accommodations and a sunset cruise.',
    image: 'https://images.pexels.com/photos/1010657/pexels-photo-1010657.jpeg',
    originalPrice: 2499,
    discountedPrice: 1999,
    discount: 20,
    categories: ['beach', 'romantic', 'cultural'],
  },
  {
    id: 2,
    title: 'Bali Adventure Package',
    description: '10 days of adventure including surfing lessons, temple visits, and jungle trekking.',
    image: 'https://images.pexels.com/photos/3225531/pexels-photo-3225531.jpeg',
    originalPrice: 1899,
    discountedPrice: 1599,
    discount: 15,
    categories: ['beach', 'adventure', 'cultural'],
  },
  {
    id: 3,
    title: 'Tokyo & Kyoto Explorer',
    description: '9 days experiencing modern Tokyo and traditional Kyoto with guided tours and authentic experiences.',
    image: 'https://images.pexels.com/photos/5759992/pexels-photo-5759992.jpeg',
    originalPrice: 2799,
    discountedPrice: 2299,
    discount: 18,
    categories: ['city', 'cultural'],
  },
  {
    id: 4,
    title: 'Peruvian Highlights Tour',
    description: '12 days exploring Peru including Machu Picchu, Sacred Valley, and Lake Titicaca.',
    image: 'https://images.pexels.com/photos/2929906/pexels-photo-2929906.jpeg',
    originalPrice: 2999,
    discountedPrice: 2499,
    discount: 17,
    categories: ['mountain', 'adventure', 'cultural'],
  },
  {
    id: 5,
    title: 'Italian Coast & Cuisine',
    description: '8 days along the Amalfi Coast with cooking classes, wine tasting, and boat excursions.',
    image: 'https://images.pexels.com/photos/4428285/pexels-photo-4428285.jpeg',
    originalPrice: 2599,
    discountedPrice: 2099,
    discount: 19,
    categories: ['beach', 'cultural', 'romantic'],
  },
  {
    id: 6,
    title: 'Moroccan Desert Adventure',
    description: '10 days exploring Marrakech, the Atlas Mountains, and camping in the Sahara Desert.',
    image: 'https://images.pexels.com/photos/4151484/pexels-photo-4151484.jpeg',
    originalPrice: 1799,
    discountedPrice: 1499,
    discount: 17,
    categories: ['adventure', 'cultural', 'desert'],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: 'Emma Thompson',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg',
    location: 'London, UK',
    rating: 5,
    content: 'Our trip to Santorini was absolutely perfect! The accommodations were luxurious, the local guides were knowledgeable, and the sunset cruise was magical. Wanderlust thought of everything!',
    destination: 'Santorini, Greece',
  },
  {
    id: 2,
    name: 'David Chen',
    avatar: 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg',
    location: 'Vancouver, Canada',
    rating: 5,
    content: 'As adventure seekers, the Bali package exceeded our expectations. From surfing to jungle trekking, every day was exciting. The guides ensured we had authentic experiences while feeling safe.',
    destination: 'Bali, Indonesia',
  },
  {
    id: 3,
    name: 'Sophia Rodriguez',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg',
    location: 'Miami, USA',
    rating: 4,
    content: 'Japan was a dream come true! The contrast between modern Tokyo and traditional Kyoto was fascinating. The cherry blossom season was perfect timing. Highly recommend this journey!',
    destination: 'Tokyo & Kyoto, Japan',
  },
];